FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_train.txt .
RUN pip install --no-cache-dir -r requirements_train.txt

COPY model_preparation.py model_testing.py ./

CMD ["python", "/app/model_testing.py"]
